// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// demo_sequence
NumericVector demo_sequence(double a, double b, double n);
RcppExport SEXP _parallelExamples_demo_sequence(SEXP aSEXP, SEXP bSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(demo_sequence(a, b, n));
    return rcpp_result_gen;
END_RCPP
}
// demo_somme
double demo_somme(NumericVector x);
RcppExport SEXP _parallelExamples_demo_somme(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(demo_somme(x));
    return rcpp_result_gen;
END_RCPP
}
// demo_vsomme
NumericVector demo_vsomme(NumericVector x, NumericVector y);
RcppExport SEXP _parallelExamples_demo_vsomme(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(demo_vsomme(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_parallelExamples_demo_sequence", (DL_FUNC) &_parallelExamples_demo_sequence, 3},
    {"_parallelExamples_demo_somme", (DL_FUNC) &_parallelExamples_demo_somme, 1},
    {"_parallelExamples_demo_vsomme", (DL_FUNC) &_parallelExamples_demo_vsomme, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_parallelExamples(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
