# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

demo_sequence <- function(a, b, n) {
    .Call(`_parallelExamples_demo_sequence`, a, b, n)
}

demo_somme <- function(x) {
    .Call(`_parallelExamples_demo_somme`, x)
}

demo_vsomme <- function(x, y) {
    .Call(`_parallelExamples_demo_vsomme`, x, y)
}

